### ISSUE TITLE
Error running script 2

### ISSUE THREAD

**Issue by jmarkovitsr** [jvcasillas/pa_4#1]
Hola @jvcasillas 
este es el link con el script que no pude correr
https://github.com/jmarkovitsr/pa_4/blob/master/scripts/2_extractVals.praat
Gracias

**Comment by jvcasillas** [comment]
Deberías usar relative paths. Me parece que tu error tiene que ver con eso.

**Comment by jmarkovitsr** [comment]
Hola Joseph,
lo primero que hice fue intentarlo con relative path y me sale el mesanje
que escribo abajo.Luego lo hice con el directorio completo y sale solo el
csv con el nombre las columnas. Gracias
[image: image.png]

**Comment by jmarkovitsr** [comment]
Joseph, ignora el correo anterior, me acaba de salir.
Disculpa

**Comment by jmarkovitsr** [comment]
En todo caso tuve que poner el path completo, en todos los script, es
porque mi computador no es Mac? Gracias

**Comment by jvcasillas** [comment]
Excelente! Buen trabajo. En algún momento quiero que juguemos con lo de los paths porque me gustaría saber cómo funciona en pc. Tenía entendido que era igual.
