### ISSUE TITLE
@jvcasillas

### ISSUE THREAD

**Issue by jmarkovitsr** [jvcasillas/pa_4#3]
Hola @jvcasillas 
estoy casi terminando (me quedan cosas), pero cuando hago knit me aparece un error en la última variable que creé (type_language) para correr un linear model, pero cuando lo corro en el markdown aparece bien. 
Gracias por los comentarios

https://github.com/jmarkovitsr/pa_4/blob/master/report/README.Rmd

**Comment by jvcasillas** [comment]
Jenifer, es mejor usar esta plataforma para explorar el error y así recibir ayuda. Puedes poner trozos de código aquí para que vea lo que intentaste hacer y el error que te salió. Así me es más fácil ayudarte.

**Comment by jmarkovitsr** [comment]
por acá te refires? Espero. Entonces como te contaba, todos los códigos me
salen bien en Rmarkown, pero cuando hago knit aparece este mensaje
[image: image.png]

**Comment by jvcasillas** [comment]
No aparece la imagen. Seguramente creaste un variable durante tu sesión pero no aparece en el Rmd. Deberías reiniciar la sesión en R de vez en cuando para evitar esto (Session > Restart R). Me imagino que después de hacer eso no te funcionará en la consola tampoco. Tienes que leer el error que te da R y usar esa información para corregir el código. Si copias y pegas el error aquí (o si intentas adjuntar la imagen otra vez) seguro que podemos averiguar qué ocurre. 

Fíjate que github te facilita todo esto... puedo usar los iconos en la parte superior de la caja de texto para incluir código... por ejemplo: 

```
my_mod <- lm(dv ~ iv, data = my_data)
```

**Comment by jmarkovitsr** [comment]
Gracias Joseph, voy a tratar de solucionarlo con tus consejos, y si no te
escribo

**Comment by jmarkovitsr** [comment]
ya lo solucioné. Había creado la variable, pero no la había declarado como
objeto.
cosas que pasan
Saludos

**Comment by jvcasillas** [comment]
Genial. 👍🏼
